services:
  - type: web
    name: restaurante-aorix
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: APP_TIMEZONE
        value: America/Lima
      - key: PERSIST_DIR
        value: /data
