services:
  - type: web
    name: el-toro-pos-final
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PERSIST_DIR
        value: /data
